Imports System.IO
Imports ICSharpCode.SharpZipLib.Zip
Imports ICSharpCode.SharpZipLib.Checksums

Partial Class CENSIMENTO_Report_TotPatrimStatoUI
    Inherits PageSetIdMode
    Dim par As New CM.Global
    Dim dt As New Data.DataTable

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Session.Item("OPERATORE") = "" Then
            Response.Write("<script>top.location.href=""../../AccessoNegato.htm""</script>")
            Exit Sub
        End If

        Dim Str As String

        Str = "<div align='center' id='dvvvPre' style='position:absolute; background-color:#ffffff; text-align:center; width:200px; height:100px; top:350px; left:450px; z-index:10; border:1px dashed #660000;"
        Str = Str & "font:verdana; font-size:10px;'><br><img src='../../Immagini/load.gif' alt='caricamento in corso' ><br>caricamento in corso..."
        Str = Str & "<" & "/div>"
        Response.Write(Str)

        If Not IsPostBack Then
            Response.Flush()
            If Request.QueryString("T") <> "-1" Then
                lbltabella.Text = "TIPOLOGIA UNITA' IMMOBILIARI (" & Request.QueryString("D").ToLower & ")"
            Else
                lbltabella.Text = "TIPOLOGIA UNITA' IMMOBILIARI (tutte le unità immobiliari)"
            End If
            DatiPatrimStatoUI()
        End If
    End Sub

    Private Sub DatiPatrimStatoUI()

        Dim s As String
        Dim n_totale As Integer
        Dim mq_totale As Double
        If Request.QueryString("C") = "-1" Then
            s = " ORDER BY SISCOM_MI.COMPLESSI_IMMOBILIARI.DENOMINAZIONE,INDIRIZZO ASC"
        ElseIf Request.QueryString("C") = "-10" Then
            s = " AND SISCOM_MI.COMPLESSI_IMMOBILIARI.ID_FILIALE =" & Request.QueryString("F") & " ORDER BY SISCOM_MI.EDIFICI.COD_EDIFICIO ASC"
        Else
            s = " AND SISCOM_MI.COMPLESSI_IMMOBILIARI.ID =" & Request.QueryString("C") & " ORDER BY SISCOM_MI.EDIFICI.COD_EDIFICIO ASC"
        End If

        Try
            par.OracleConn.Open()
            par.SettaCommand(par)

            Dim RIGA As System.Data.DataRow
            Dim RIGA2 As System.Data.DataRow
            
            'variabili per i totali dei civici
            Dim contRegCIV As Integer = 0
            Dim contReg2CIV As Double = 0
            Dim contAbusCIV As Integer = 0
            Dim contAbus2CIV As Double = 0
            Dim contLibeCIV As Integer = 0
            Dim contLibe2CIV As Double = 0
            Dim contIndefCIV As Integer = 0
            Dim contIndef2CIV As Double = 0
            Dim contInagCIV As Integer = 0
            Dim contInag2CIV As Double = 0
            Dim contComCIV As Integer = 0
            Dim contCom2CIV As Double = 0
            Dim contTotCIV As Integer = 0
            Dim contTot2CIV As Double = 0

            'variabili per i totali dei complessi
            Dim contRegCOMPL As Integer = 0
            Dim contReg2COMPL As Double = 0
            Dim contAbusCOMPL As Integer = 0
            Dim contAbus2COMPL As Double = 0
            Dim contLibeCOMPL As Integer = 0
            Dim contLibe2COMPL As Double = 0
            Dim contIndefCOMPL As Integer = 0
            Dim contIndef2COMPL As Double = 0
            Dim contInagCOMPL As Integer = 0
            Dim contInag2COMPL As Double = 0
            Dim contComCOMPL As Integer = 0
            Dim contCom2COMPL As Double = 0
            Dim contTotCOMPL As Integer = 0
            Dim contTot2COMPL As Double = 0

            Dim contRegGENER As Integer = 0
            Dim contReg2GENER As Double = 0
            Dim contAbusGENER As Integer = 0
            Dim contAbus2GENER As Double = 0
            Dim contLibeGENER As Integer = 0
            Dim contLibe2GENER As Double = 0
            Dim contIndefGENER As Integer = 0
            Dim contIndef2GENER As Double = 0
            Dim contInagGENER As Integer = 0
            Dim contInag2GENER As Double = 0
            Dim contComGENER As Integer = 0
            Dim contCom2GENER As Double = 0
            Dim contTotGENER As Integer = 0
            Dim contTot2GENER As Double = 0

            dt.Columns.Add("ID_COMPLESSO", Type.GetType("System.String"))
            dt.Columns.Add("DENOMINAZIONE", Type.GetType("System.String"))
            dt.Columns.Add("COD_EDIFICIO", Type.GetType("System.String"))
            dt.Columns.Add("INDIRIZZO", Type.GetType("System.String"))
            dt.Columns.Add("N_REGOLARE")
            dt.Columns.Add("MQ_REGOLARE")
            dt.Columns.Add("N_ABUSIVA")
            dt.Columns.Add("MQ_ABUSIVA")
            dt.Columns.Add("N_LIBERA")
            dt.Columns.Add("MQ_LIBERA")
            dt.Columns.Add("N_INDEF")
            dt.Columns.Add("MQ_INDEF")
            dt.Columns.Add("N_INAG")
            dt.Columns.Add("MQ_INAG")
            dt.Columns.Add("N_COMUNI")
            dt.Columns.Add("MQ_COMUNI")
            dt.Columns.Add("N_TOTALE")
            dt.Columns.Add("MQ_TOTALE")

            Dim dt2 As New Data.DataTable
            par.cmd.CommandText = "SELECT SISCOM_MI.COMPLESSI_IMMOBILIARI.DENOMINAZIONE,SISCOM_MI.EDIFICI.COD_EDIFICIO,SISCOM_MI.INDIRIZZI.DESCRIZIONE||', '||INDIRIZZI.CIVICO AS INDIRIZZO,SISCOM_MI.COMPLESSI_IMMOBILIARI.ID AS ID_COMPLESSO FROM SISCOM_MI.COMPLESSI_IMMOBILIARI,SISCOM_MI.INDIRIZZI,SISCOM_MI.EDIFICI WHERE SISCOM_MI.COMPLESSI_IMMOBILIARI.ID = SISCOM_MI.EDIFICI.ID_COMPLESSO AND SISCOM_MI.EDIFICI.ID_INDIRIZZO_PRINCIPALE = SISCOM_MI.INDIRIZZI.ID AND SISCOM_MI.COMPLESSI_IMMOBILIARI.ID <> 1 " & s & ""
            Dim da As Oracle.DataAccess.Client.OracleDataAdapter
            da = New Oracle.DataAccess.Client.OracleDataAdapter(par.cmd)
            da.Fill(dt2)
            DataGrid1.DataSource = dt2

            For i As Integer = 0 To dt2.Rows.Count - 1
                RIGA = dt.NewRow()
                RIGA.Item("DENOMINAZIONE") = dt2.Rows(i).Item(0)
                RIGA.Item("COD_EDIFICIO") = dt2.Rows(i).Item(1)
                RIGA.Item("INDIRIZZO") = dt2.Rows(i).Item(2)
                RIGA.Item("ID_COMPLESSO") = dt2.Rows(i).Item(3)

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_REGOLARE FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                Else
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_REGOLARE FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = '" & Request.QueryString("T") & "' AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                End If
                Dim myReader2 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_REGOLARE") = par.IfNull(myReader2("N_REGOLARE"), "0")
                End If
                myReader2.Close()

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_REGOLARE") = CDbl(par.IfNull(myReader3("MQ_REGOLARE"), "0")) + CDbl(par.IfNull(myReader4("MQ_REGOLARE"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_REGOLARE FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'OCCU' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_REGOLARE") = par.IfNull(myReader2("MQ_REGOLARE"), "0")
                    End If
                    myReader2.Close()
                End If


                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_ABUSIVA FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                Else
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_ABUSIVA FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = '" & Request.QueryString("T") & "' AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                End If
                myReader2 = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_ABUSIVA") = par.IfNull(myReader2("N_ABUSIVA"), "0")
                End If
                myReader2.Close()

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_ABUSIVA") = CDbl(par.IfNull(myReader3("MQ_ABUSIVA"), "0")) + CDbl(par.IfNull(myReader4("MQ_ABUSIVA"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_ABUSIVA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LOCA' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_ABUSIVA") = par.IfNull(myReader2("MQ_ABUSIVA"), "0")
                    End If
                    myReader2.Close()
                End If

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_LIBERA FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                Else
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_LIBERA FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = '" & Request.QueryString("T") & "' AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                End If
                myReader2 = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_LIBERA") = par.IfNull(myReader2("N_LIBERA"), "0")
                End If
                myReader2.Close()

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_LIBERA") = CDbl(par.IfNull(myReader3("MQ_LIBERA"), "0")) + CDbl(par.IfNull(myReader4("MQ_LIBERA"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_LIBERA FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'LIBE' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_LIBERA") = par.IfNull(myReader2("MQ_LIBERA"), "0")
                    End If
                    myReader2.Close()
                End If

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_INDEF FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                Else
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_INDEF FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = '" & Request.QueryString("T") & "' AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                End If
                myReader2 = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_INDEF") = par.IfNull(myReader2("N_INDEF"), "0")
                End If
                myReader2.Close()


                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_INDEF") = CDbl(par.IfNull(myReader3("MQ_INDEF"), "0")) + CDbl(par.IfNull(myReader4("MQ_INDEF"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INDEF FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'INDEF' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_INDEF") = par.IfNull(myReader2("MQ_INDEF"), "0")
                    End If
                    myReader2.Close()
                End If


                'Nuova colonna INAGIBILI 03/02/2012
                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_INAG FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                Else
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_IMMOBILIARI.ID),'9G999G999')) AS N_INAG FROM SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.EDIFICI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = '" & Request.QueryString("T") & "' AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                End If
                myReader2 = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_INAG") = par.IfNull(myReader2("N_INAG"), "0")
                End If
                myReader2.Close()


                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA <>'AL' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_INAG") = CDbl(par.IfNull(myReader3("MQ_INAG"), "0")) + CDbl(par.IfNull(myReader4("MQ_INAG"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_INAG FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_IMMOBILIARI,SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI,SISCOM_MI.TIPO_DISPONIBILITA WHERE SISCOM_MI.UNITA_IMMOBILIARI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPO_DISPONIBILITA = SISCOM_MI.TIPO_DISPONIBILITA.COD AND SISCOM_MI.STATO_UI(SISCOM_MI.UNITA_IMMOBILIARI.ID) = 'NAGI' AND SISCOM_MI.DIMENSIONI.ID_UNITA_IMMOBILIARE = SISCOM_MI.UNITA_IMMOBILIARI.ID AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA = SISCOM_MI.TIPOLOGIA_UNITA_IMMOBILIARI.COD AND SISCOM_MI.UNITA_IMMOBILIARI.COD_TIPOLOGIA ='" & Request.QueryString("T") & "' AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_INAG") = par.IfNull(myReader2("MQ_INAG"), "0")
                    End If
                    myReader2.Close()
                End If
                'FINE Nuova colonna INAGIBILI 03/02/2012


                par.cmd.CommandText = "SELECT TRIM(TO_CHAR(COUNT(SISCOM_MI.UNITA_COMUNI.ID),'9G999G999')) AS N_COMUNI FROM SISCOM_MI.UNITA_COMUNI,SISCOM_MI.EDIFICI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                myReader2 = par.cmd.ExecuteReader()
                If myReader2.Read Then
                    RIGA.Item("N_COMUNI") = par.IfNull(myReader2("N_COMUNI"), "0")
                End If
                myReader2.Close()

                If Request.QueryString("T") = "-1" Then
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader3 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Dim myReader4 As Oracle.DataAccess.Client.OracleDataReader = par.cmd.ExecuteReader()
                    If myReader3.Read Or myReader4.Read Then
                        RIGA.Item("MQ_COMUNI") = CDbl(par.IfNull(myReader3("MQ_COMUNI"), "0")) + CDbl(par.IfNull(myReader4("MQ_COMUNI"), "0"))
                    End If
                    myReader3.Close()
                    myReader4.Close()
                Else
                    If Request.QueryString("T") = "AL" Then
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    Else
                        'par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_UR' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                        par.cmd.CommandText = "SELECT TRIM(TO_CHAR(SUM(SISCOM_MI.DIMENSIONI.VALORE),'9G999G990D99')) AS MQ_COMUNI FROM SISCOM_MI.DIMENSIONI,SISCOM_MI.EDIFICI,SISCOM_MI.UNITA_COMUNI WHERE SISCOM_MI.UNITA_COMUNI.ID_EDIFICIO = SISCOM_MI.EDIFICI.ID AND SISCOM_MI.DIMENSIONI.ID_UNITA_COMUNE = SISCOM_MI.UNITA_COMUNI.ID AND SISCOM_MI.DIMENSIONI.COD_TIPOLOGIA = 'SUP_NETTA' AND SISCOM_MI.EDIFICI.COD_EDIFICIO =" & dt2.Rows(i).Item(1) & ""
                    End If
                    myReader2 = par.cmd.ExecuteReader()
                    If myReader2.Read Then
                        RIGA.Item("MQ_COMUNI") = par.IfNull(myReader2("MQ_COMUNI"), "0")
                    End If
                    myReader2.Close()
                End If
                
                n_totale = CInt(RIGA.Item("N_REGOLARE")) + CInt(RIGA.Item("N_ABUSIVA")) + CInt(RIGA.Item("N_LIBERA")) + CInt(RIGA.Item("N_INDEF")) + CInt(RIGA.Item("N_INAG")) + CInt(RIGA.Item("N_COMUNI"))
                mq_totale = CDbl(RIGA.Item("MQ_REGOLARE")) + CDbl(RIGA.Item("MQ_ABUSIVA")) + CDbl(RIGA.Item("MQ_LIBERA")) + CDbl(RIGA.Item("MQ_INDEF")) + CDbl(RIGA.Item("MQ_INAG")) + CDbl(RIGA.Item("MQ_COMUNI"))
                RIGA.Item("N_TOTALE") = Format(n_totale, "##,##0")
                RIGA.Item("MQ_TOTALE") = Format(mq_totale, "##,##0.00")

                If Request.QueryString("TOT") = "0" Or Request.QueryString("TOT") = "3" Then
                    dt.Rows.Add(RIGA)
                End If

                contRegCIV = contRegCIV + RIGA.Item("N_REGOLARE")
                contReg2CIV = contReg2CIV + RIGA.Item("MQ_REGOLARE")
                contAbusCIV = contAbusCIV + RIGA.Item("N_ABUSIVA")
                contAbus2CIV = contAbus2CIV + RIGA.Item("MQ_ABUSIVA")
                contLibeCIV = contLibeCIV + RIGA.Item("N_LIBERA")
                contLibe2CIV = contLibe2CIV + RIGA.Item("MQ_LIBERA")
                contIndefCIV = contIndefCIV + RIGA.Item("N_INDEF")
                contIndef2CIV = contIndef2CIV + RIGA.Item("MQ_INDEF")
                contInagCIV = contInagCIV + RIGA.Item("N_INAG")
                contInag2CIV = contInag2CIV + RIGA.Item("MQ_INAG")
                contComCIV = contComCIV + RIGA.Item("N_COMUNI")
                contCom2CIV = contCom2CIV + RIGA.Item("MQ_COMUNI")
                contTotCIV = contTotCIV + RIGA.Item("N_TOTALE")
                contTot2CIV = contTot2CIV + RIGA.Item("MQ_TOTALE")

                contRegCOMPL = contRegCOMPL + RIGA.Item("N_REGOLARE")
                contReg2COMPL = contReg2COMPL + RIGA.Item("MQ_REGOLARE")
                contAbusCOMPL = contAbusCOMPL + RIGA.Item("N_ABUSIVA")
                contAbus2COMPL = contAbus2COMPL + RIGA.Item("MQ_ABUSIVA")
                contLibeCOMPL = contLibeCOMPL + RIGA.Item("N_LIBERA")
                contLibe2COMPL = contLibe2COMPL + RIGA.Item("MQ_LIBERA")
                contIndefCOMPL = contIndefCOMPL + RIGA.Item("N_INDEF")
                contIndef2COMPL = contIndef2COMPL + RIGA.Item("MQ_INDEF")
                contInagCOMPL = contInagCOMPL + RIGA.Item("N_INAG")
                contInag2COMPL = contInag2COMPL + RIGA.Item("MQ_INAG")
                contComCOMPL = contComCOMPL + RIGA.Item("N_COMUNI")
                contCom2COMPL = contCom2COMPL + RIGA.Item("MQ_COMUNI")
                contTotCOMPL = contTotCOMPL + RIGA.Item("N_TOTALE")
                contTot2COMPL = contTot2COMPL + RIGA.Item("MQ_TOTALE")

                contRegGENER = contRegGENER + RIGA.Item("N_REGOLARE")
                contReg2GENER = contReg2GENER + RIGA.Item("MQ_REGOLARE")
                contAbusGENER = contAbusGENER + RIGA.Item("N_ABUSIVA")
                contAbus2GENER = contAbus2GENER + RIGA.Item("MQ_ABUSIVA")
                contLibeGENER = contLibeGENER + RIGA.Item("N_LIBERA")
                contLibe2GENER = contLibe2GENER + RIGA.Item("MQ_LIBERA")
                contIndefGENER = contIndefGENER + RIGA.Item("N_INDEF")
                contIndef2GENER = contIndef2GENER + RIGA.Item("MQ_INDEF")
                contInagGENER = contInagGENER + RIGA.Item("N_INAG")
                contInag2GENER = contInag2GENER + RIGA.Item("MQ_INAG")
                contComGENER = contComGENER + RIGA.Item("N_COMUNI")
                contCom2GENER = contCom2GENER + RIGA.Item("MQ_COMUNI")
                contTotGENER = contTotGENER + RIGA.Item("N_TOTALE")
                contTot2GENER = contTot2GENER + RIGA.Item("MQ_TOTALE")

                If i < dt2.Rows.Count - 1 Then
                    If dt2.Rows(i).Item(2) <> dt2.Rows(i + 1).Item(2) Then
                        RIGA2 = dt.NewRow()
                        If Request.QueryString("TOT") <> "0" Then
                            RIGA2.Item("DENOMINAZIONE") = RIGA.Item("DENOMINAZIONE")
                            RIGA2.Item("INDIRIZZO") = RIGA.Item("INDIRIZZO")
                        End If
                        RIGA2.Item("COD_EDIFICIO") = "TOTALE CIVICO"
                        RIGA2.Item("N_REGOLARE") = Format(contRegCIV, "##,##0")
                        RIGA2.Item("MQ_REGOLARE") = Format(contReg2CIV, "##,##0.00")
                        RIGA2.Item("N_ABUSIVA") = Format(contAbusCIV, "##,##0")
                        RIGA2.Item("MQ_ABUSIVA") = Format(contAbus2CIV, "##,##0.00")
                        RIGA2.Item("N_LIBERA") = Format(contLibeCIV, "##,##0")
                        RIGA2.Item("MQ_LIBERA") = Format(contLibe2CIV, "##,##0.00")
                        RIGA2.Item("N_INDEF") = Format(contIndefCIV, "##,##0")
                        RIGA2.Item("MQ_INDEF") = Format(contIndef2CIV, "##,##0.00")
                        RIGA2.Item("N_INAG") = Format(contInagCIV, "##,##0")
                        RIGA2.Item("MQ_INAG") = Format(contInag2CIV, "##,##0.00")
                        RIGA2.Item("N_COMUNI") = Format(contComCIV, "##,##0")
                        RIGA2.Item("MQ_COMUNI") = Format(contCom2CIV, "##,##0.00")
                        RIGA2.Item("N_TOTALE") = Format(contTotCIV, "##,##0")
                        RIGA2.Item("MQ_TOTALE") = Format(contTot2CIV, "##,##0.00")
                        If Request.QueryString("TOT") = "1" Or Request.QueryString("TOT") = "0" Then
                            dt.Rows.Add(RIGA2)
                        End If
                        contRegCIV = 0
                        contReg2CIV = 0
                        contAbusCIV = 0
                        contAbus2CIV = 0
                        contLibeCIV = 0
                        contLibe2CIV = 0
                        contIndefCIV = 0
                        contIndef2CIV = 0
                        contInagCIV = 0
                        contInag2CIV = 0
                        contComCIV = 0
                        contCom2CIV = 0
                        contTotCIV = 0
                        contTot2CIV = 0
                    End If
                    If dt2.Rows(i).Item(3) <> dt2.Rows(i + 1).Item(3) Then
                        RIGA2 = dt.NewRow()
                        RIGA2.Item("DENOMINAZIONE") = RIGA.Item("DENOMINAZIONE")
                        RIGA2.Item("INDIRIZZO") = "TOTALE COMPLESSO"
                        RIGA2.Item("N_REGOLARE") = Format(contRegCOMPL, "##,##0")
                        RIGA2.Item("MQ_REGOLARE") = Format(contReg2COMPL, "##,##0.00")
                        RIGA2.Item("N_ABUSIVA") = Format(contAbusCOMPL, "##,##0")
                        RIGA2.Item("MQ_ABUSIVA") = Format(contAbus2COMPL, "##,##0.00")
                        RIGA2.Item("N_LIBERA") = Format(contLibeCOMPL, "##,##0")
                        RIGA2.Item("MQ_LIBERA") = Format(contLibe2COMPL, "##,##0.00")
                        RIGA2.Item("N_INDEF") = Format(contIndefCOMPL, "##,##0")
                        RIGA2.Item("MQ_INDEF") = Format(contIndef2COMPL, "##,##0.00")
                        RIGA2.Item("N_INAG") = Format(contInagCOMPL, "##,##0")
                        RIGA2.Item("MQ_INAG") = Format(contInag2COMPL, "##,##0.00")

                        RIGA2.Item("N_COMUNI") = Format(contComCOMPL, "##,##0")
                        RIGA2.Item("MQ_COMUNI") = Format(contCom2COMPL, "##,##0.00")
                        RIGA2.Item("N_TOTALE") = Format(contTotCOMPL, "##,##0")
                        RIGA2.Item("MQ_TOTALE") = Format(contTot2COMPL, "##,##0.00")
                        If Request.QueryString("TOT") = "2" Or Request.QueryString("TOT") = "0" Then
                            dt.Rows.Add(RIGA2)
                        End If
                        contRegCOMPL = 0
                        contReg2COMPL = 0
                        contAbusCOMPL = 0
                        contAbus2COMPL = 0
                        contLibeCOMPL = 0
                        contLibe2COMPL = 0
                        contIndefCOMPL = 0
                        contIndef2COMPL = 0
                        contInagCOMPL = 0
                        contInag2COMPL = 0
                        contComCOMPL = 0
                        contCom2COMPL = 0
                        contTotCOMPL = 0
                        contTot2COMPL = 0
                    End If
                Else
                    If dt2.Rows(i).Item(2) = dt2.Rows(i).Item(2) Then
                        RIGA2 = dt.NewRow()
                        If Request.QueryString("TOT") <> "0" Then
                            RIGA2.Item("DENOMINAZIONE") = RIGA.Item("DENOMINAZIONE")
                            RIGA2.Item("INDIRIZZO") = RIGA.Item("INDIRIZZO")
                        End If
                        RIGA2.Item("COD_EDIFICIO") = "TOTALE CIVICO"
                        RIGA2.Item("N_REGOLARE") = Format(contRegCIV, "##,##0")
                        RIGA2.Item("MQ_REGOLARE") = Format(contReg2CIV, "##,##0.00")
                        RIGA2.Item("N_ABUSIVA") = Format(contAbusCIV, "##,##0")
                        RIGA2.Item("MQ_ABUSIVA") = Format(contAbus2CIV, "##,##0.00")
                        RIGA2.Item("N_LIBERA") = Format(contLibeCIV, "##,##0")
                        RIGA2.Item("MQ_LIBERA") = Format(contLibe2CIV, "##,##0.00")
                        RIGA2.Item("N_INDEF") = Format(contIndefCIV, "##,##0")
                        RIGA2.Item("MQ_INDEF") = Format(contIndef2CIV, "##,##0.00")
                        RIGA2.Item("N_INAG") = Format(contInagCIV, "##,##0")
                        RIGA2.Item("MQ_INAG") = Format(contInag2CIV, "##,##0.00")

                        RIGA2.Item("N_COMUNI") = Format(contComCIV, "##,##0")
                        RIGA2.Item("MQ_COMUNI") = Format(contCom2CIV, "##,##0.00")
                        RIGA2.Item("N_TOTALE") = Format(contTotCIV, "##,##0")
                        RIGA2.Item("MQ_TOTALE") = Format(contTot2CIV, "##,##0.00")
                        If Request.QueryString("TOT") = "1" Or Request.QueryString("TOT") = "0" Then
                            dt.Rows.Add(RIGA2)
                        End If
                        contRegCIV = 0
                        contReg2CIV = 0
                        contAbusCIV = 0
                        contAbus2CIV = 0
                        contLibeCIV = 0
                        contLibe2CIV = 0
                        contIndefCIV = 0
                        contIndef2CIV = 0
                        contInagCIV = 0
                        contInag2CIV = 0
                        contComCIV = 0
                        contCom2CIV = 0
                        contTotCIV = 0
                        contTot2CIV = 0
                    End If

                    RIGA2 = dt.NewRow()
                    RIGA2.Item("DENOMINAZIONE") = RIGA.Item("DENOMINAZIONE")
                    RIGA2.Item("INDIRIZZO") = "TOTALE COMPLESSO"
                    RIGA2.Item("N_REGOLARE") = Format(contRegCOMPL, "##,##0")
                    RIGA2.Item("MQ_REGOLARE") = Format(contReg2COMPL, "##,##0.00")
                    RIGA2.Item("N_ABUSIVA") = Format(contAbusCOMPL, "##,##0")
                    RIGA2.Item("MQ_ABUSIVA") = Format(contAbus2COMPL, "##,##0.00")
                    RIGA2.Item("N_LIBERA") = Format(contLibeCOMPL, "##,##0")
                    RIGA2.Item("MQ_LIBERA") = Format(contLibe2COMPL, "##,##0.00")
                    RIGA2.Item("N_INDEF") = Format(contIndefCOMPL, "##,##0")
                    RIGA2.Item("MQ_INDEF") = Format(contIndef2COMPL, "##,##0.00")
                    RIGA2.Item("N_INAG") = Format(contInagCOMPL, "##,##0")
                    RIGA2.Item("MQ_INAG") = Format(contInag2COMPL, "##,##0.00")
                    RIGA2.Item("N_COMUNI") = Format(contComCOMPL, "##,##0")
                    RIGA2.Item("MQ_COMUNI") = Format(contCom2COMPL, "##,##0.00")
                    RIGA2.Item("N_TOTALE") = Format(contTotCOMPL, "##,##0")
                    RIGA2.Item("MQ_TOTALE") = Format(contTot2COMPL, "##,##0.00")
                    If Request.QueryString("TOT") = "2" Or Request.QueryString("TOT") = "0" Then
                        dt.Rows.Add(RIGA2)
                    End If
                    contRegCOMPL = 0
                    contReg2COMPL = 0
                    contAbusCOMPL = 0
                    contAbus2COMPL = 0
                    contLibeCOMPL = 0
                    contLibe2COMPL = 0
                    contIndefCOMPL = 0
                    contIndef2COMPL = 0
                    contInagCOMPL = 0
                    contInag2COMPL = 0
                    contComCOMPL = 0
                    contCom2COMPL = 0
                    contTotCOMPL = 0
                    contTot2COMPL = 0
                End If

                If Request.QueryString("C") = "-1" And i = dt2.Rows.Count - 1 Then
                    ''RIGA = dt.NewRow()
                    'dt.Rows.Add(RIGA)
                    RIGA = dt.NewRow()
                    RIGA.Item("DENOMINAZIONE") = "TOTALE GENERALE"
                    RIGA.Item("N_REGOLARE") = Format(contRegGENER, "##,##0")
                    RIGA.Item("MQ_REGOLARE") = Format(contReg2GENER, "##,##0.00")
                    RIGA.Item("N_ABUSIVA") = Format(contAbusGENER, "##,##0")
                    RIGA.Item("MQ_ABUSIVA") = Format(contAbus2GENER, "##,##0.00")
                    RIGA.Item("N_LIBERA") = Format(contLibeGENER, "##,##0")
                    RIGA.Item("MQ_LIBERA") = Format(contLibe2GENER, "##,##0.00")
                    RIGA.Item("N_INDEF") = Format(contIndefGENER, "##,##0")
                    RIGA.Item("MQ_INDEF") = Format(contIndef2GENER, "##,##0.00")
                    RIGA.Item("N_INAG") = Format(contInagGENER, "##,##0")
                    RIGA.Item("MQ_INAG") = Format(contInag2GENER, "##,##0.00")

                    RIGA.Item("N_COMUNI") = Format(contComGENER, "##,##0")
                    RIGA.Item("MQ_COMUNI") = Format(contCom2GENER, "##,##0.00")
                    RIGA.Item("N_TOTALE") = Format(contTotGENER, "##,##0")
                    RIGA.Item("MQ_TOTALE") = Format(contTot2GENER, "##,##0.00")
                    dt.Rows.Add(RIGA)
                End If

            Next

            Session.Add("MIADT", dt)
            DataGrid1.DataSource = dt
            DataGrid1.DataBind()

            If Request.QueryString("TOT") = "1" Or Request.QueryString("TOT") = "2" Or Request.QueryString("TOT") = "3" Then
                DataGrid1.AlternatingItemStyle.BackColor = Drawing.Color.Lavender
            End If

            If Request.QueryString("TOT") = "0" Then
                For Each di As DataGridItem In DataGrid1.Items
                    If di.Cells(3).Text.Contains("TOTALE") Then
                        di.ForeColor = Drawing.Color.Red
                        di.Cells(3).Font.Bold = True
                    End If
                    If di.Cells(2).Text.Contains("TOTALE") Then
                        di.BackColor = Drawing.Color.Gainsboro
                        di.ForeColor = Drawing.Color.Black
                        For j As Integer = 0 To di.Cells.Count - 1
                            di.Cells(j).Font.Bold = True
                        Next
                    End If
                    If di.Cells(1).Text.Contains("TOTALE") Then
                        di.BackColor = Drawing.Color.RoyalBlue
                        di.ForeColor = Drawing.Color.White
                        di.Cells(1).Font.Underline = True
                        For j As Integer = 0 To di.Cells.Count - 1
                            di.Cells(j).Font.Bold = True
                        Next
                    End If
                Next
            Else
                For Each di As DataGridItem In DataGrid1.Items
                    If di.Cells(1).Text.Contains("TOTALE") Then
                        di.BackColor = Drawing.Color.RoyalBlue
                        di.ForeColor = Drawing.Color.White
                        di.Cells(1).Font.Underline = True
                        For j As Integer = 0 To di.Cells.Count - 1
                            di.Cells(j).Font.Bold = True
                        Next
                    End If
                Next
            End If

            par.OracleConn.Close()
            Oracle.DataAccess.Client.OracleConnection.ClearAllPools()

        Catch ex As Exception
            Response.Write(ex.Message)
            par.OracleConn.Close()
            Oracle.DataAccess.Client.OracleConnection.ClearAllPools()
        End Try

    End Sub

    
    Protected Sub btnExport_Click(ByVal sender As Object, ByVal e As System.Web.UI.ImageClickEventArgs) Handles btnExport.Click
        Try
            Dim myExcelFile As New CM.ExcelFile
            Dim i As Long
            Dim K As Long
            Dim sNomeFile As String
            Dim row As System.Data.DataRow

            dt = CType(HttpContext.Current.Session.Item("MIADT"), Data.DataTable)
            sNomeFile = "Tot_dati_patrim_statoUI" & Format(Now, "yyyyMMddHHmm")
            i = 0

            With myExcelFile

                .CreateFile(Server.MapPath("..\..\FileTemp\" & sNomeFile & ".xls"))
                .PrintGridLines = False
                .SetMargin(CM.ExcelFile.MarginTypes.xlsTopMargin, 1.5)
                .SetMargin(CM.ExcelFile.MarginTypes.xlsLeftMargin, 1.5)
                .SetMargin(CM.ExcelFile.MarginTypes.xlsRightMargin, 1.5)
                .SetMargin(CM.ExcelFile.MarginTypes.xlsBottomMargin, 1.5)
                .SetDefaultRowHeight(14)
                .SetFont("Arial", 10, CM.ExcelFile.FontFormatting.xlsNoFormat)
                .SetFont("Arial", 10, CM.ExcelFile.FontFormatting.xlsBold)
                .SetFont("Arial", 10, CM.ExcelFile.FontFormatting.xlsBold + CM.ExcelFile.FontFormatting.xlsUnderline)
                '.SetFont("Courier", 16, CM.ExcelFile.FontFormatting.xlsBold + CM.ExcelFile.FontFormatting.xlsItalic)
                .SetColumnWidth(1, 1, 30)
                .SetColumnWidth(2, 2, 40)
                .SetColumnWidth(3, 3, 15)
                .SetColumnWidth(4, 4, 24)
                .SetColumnWidth(5, 5, 24)
                .SetColumnWidth(6, 6, 24)
                .SetColumnWidth(7, 7, 24)
                .SetColumnWidth(8, 8, 16)
                .SetColumnWidth(9, 9, 15)
                .SetColumnWidth(10, 10, 15)
                .SetColumnWidth(11, 11, 15)
                .SetColumnWidth(12, 12, 22)
                .SetColumnWidth(13, 13, 20)
                .SetColumnWidth(14, 14, 22)
                .SetColumnWidth(15, 15, 20)
                .SetColumnWidth(16, 16, 15)
                .SetColumnWidth(17, 17, 15)

                If Request.QueryString("D") <> "TUTTO IL PATRIMONIIO" Then
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 1, 7, "Totalizzazioni dati patrimoniali (" & Request.QueryString("D").ToLower & ")", 0)
                Else
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 1, 7, "Totalizzazioni dati patrimoniali (tutte le unità immobiliari)", 0)
                End If
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 1, "COMPLESSO", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 2, "INDIRIZZO E NUM. CIVICO", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 3, "EDIFICIO", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 4, "NUM. OCC. REGOLARE", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 5, "MQ OCC. REGOLARE", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 6, "NUM. OCC. ABUSIVAM.", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 7, "MQ OCC. ABUSIVAM.", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 8, "NUM. LIBERI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 9, "MQ LIBERI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 10, "NUM. NON DEF.", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 11, "MQ NON DEF.", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 12, "NUM. INAGIBILI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 13, "MQ INAGIBILI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 14, "NUM. PARTI COMUNI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 15, "MQ PARTI COMUNI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 16, "NUM. TOTALI", 0)
                .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsCentreAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, 3, 17, "MQ TOTALI", 0)

                K = 4
                For Each row In dt.Rows
                    If dt.Rows(i).Item("DENOMINAZIONE").ToString.Contains("GENERALE") Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont2, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 1, par.IfNull(dt.Rows(i).Item("DENOMINAZIONE"), ""))
                    Else
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 1, par.IfNull(dt.Rows(i).Item("DENOMINAZIONE"), ""))
                    End If
                    If dt.Rows(i).Item("INDIRIZZO").ToString.Contains("COMPLESSO") And Request.QueryString("TOT") = "0" Then
                        '.WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 1, par.IfNull(dt.Rows(i).Item("DENOMINAZIONE"), ""))
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 2, par.IfNull(dt.Rows(i).Item("INDIRIZZO"), ""))
                    End If
                    If dt.Rows(i).Item("INDIRIZZO").ToString.Contains("COMPLESSO") = False Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 2, par.IfNull(dt.Rows(i).Item("INDIRIZZO"), ""))
                    End If
                    If dt.Rows(i).Item("INDIRIZZO").ToString.Contains("COMPLESSO") And Request.QueryString("TOT") <> "0" Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 2, par.IfNull(dt.Rows(i).Item("INDIRIZZO"), ""))
                    End If
                    If dt.Rows(i).Item("COD_EDIFICIO").ToString.Contains("CIVICO") And Request.QueryString("TOT") = "0" Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont1, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 3, par.IfNull(dt.Rows(i).Item("COD_EDIFICIO"), ""))
                    End If
                    If dt.Rows(i).Item("COD_EDIFICIO").ToString.Contains("CIVICO") And Request.QueryString("TOT") <> "0" Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 3, par.IfNull(dt.Rows(i).Item("COD_EDIFICIO"), ""))
                    End If
                    If dt.Rows(i).Item("COD_EDIFICIO").ToString.Contains("CIVICO") = False Then
                        .WriteValue(CM.ExcelFile.ValueTypes.xlsText, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsLeftAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 3, par.IfNull(dt.Rows(i).Item("COD_EDIFICIO"), ""))
                    End If
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 4, par.IfNull(dt.Rows(i).Item("N_REGOLARE"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 5, par.IfNull(dt.Rows(i).Item("MQ_REGOLARE"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 6, par.IfNull(dt.Rows(i).Item("N_ABUSIVA"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 7, par.IfNull(dt.Rows(i).Item("MQ_ABUSIVA"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 8, par.IfNull(dt.Rows(i).Item("N_LIBERA"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 9, par.IfNull(dt.Rows(i).Item("MQ_LIBERA"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 10, par.IfNull(dt.Rows(i).Item("N_INDEF"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 11, par.IfNull(dt.Rows(i).Item("MQ_INDEF"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 12, par.IfNull(dt.Rows(i).Item("N_INAG"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 13, par.IfNull(dt.Rows(i).Item("MQ_INAG"), "0"))

                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 14, par.IfNull(dt.Rows(i).Item("N_COMUNI"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 15, par.IfNull(dt.Rows(i).Item("MQ_COMUNI"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 16, par.IfNull(dt.Rows(i).Item("N_TOTALE"), "0"))
                    .WriteValue(CM.ExcelFile.ValueTypes.xlsNumber, CM.ExcelFile.CellFont.xlsFont0, CM.ExcelFile.CellAlignment.xlsRightAlign, CM.ExcelFile.CellHiddenLocked.xlsNormal, K, 17, par.IfNull(dt.Rows(i).Item("MQ_TOTALE"), "0"))
                    i = i + 1
                    K = K + 1
                Next
                .CloseFile()
            End With

            Dim objCrc32 As New Crc32()
            Dim strmZipOutputStream As ZipOutputStream
            Dim zipfic As String

            zipfic = Server.MapPath("..\..\FileTemp\" & sNomeFile & ".zip")

            strmZipOutputStream = New ZipOutputStream(File.Create(zipfic))
            strmZipOutputStream.SetLevel(6)

            Dim strFile As String
            strFile = Server.MapPath("..\..\FileTemp\" & sNomeFile & ".xls")
            Dim strmFile As FileStream = File.OpenRead(strFile)
            Dim abyBuffer(Convert.ToInt32(strmFile.Length - 1)) As Byte
            '
            strmFile.Read(abyBuffer, 0, abyBuffer.Length)

            Dim sFile As String = Path.GetFileName(strFile)
            Dim theEntry As ZipEntry = New ZipEntry(sFile)
            Dim fi As New FileInfo(strFile)
            theEntry.DateTime = fi.LastWriteTime
            theEntry.Size = strmFile.Length
            strmFile.Close()
            objCrc32.Reset()
            objCrc32.Update(abyBuffer)
            theEntry.Crc = objCrc32.Value
            strmZipOutputStream.PutNextEntry(theEntry)
            strmZipOutputStream.Write(abyBuffer, 0, abyBuffer.Length)
            strmZipOutputStream.Finish()
            strmZipOutputStream.Close()

            File.Delete(strFile)
            Response.Redirect("..\..\FileTemp\" & sNomeFile & ".zip")

        Catch ex As Exception
            Response.Write(ex.Message)
        End Try
    End Sub
End Class
