<%@ Page Language="VB" AutoEventWireup="false" CodeFile="StampaSolleciti.ASPX.vb" Inherits="Contratti_Report_StampaSolleciti" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Solleciti</title>
</head>
<body>
    <form id="form1" runat="server">
    
        <img style="cursor:pointer" alt="" src="../../NuoveImm/Img_ExportExcel.png" onclick="window.open('SollecitiExport.aspx','','');"/><p>
</p>



    </form>
    


</body>
    <script  language="javascript" type="text/javascript">
    document.getElementById('dvvvPre').style.visibility='hidden';
    </script>
</html>
